# load("@rules_cc//cc:defs.bzl", "cc_library")
# load("//tools:cpplint.bzl", "cpplint")

# package(default_visibility = ["//visibility:public"])

# cc_binary(
#     name = "libLPMS_driver_component.so",
#     linkopts = ["-shared"],
#     linkstatic = False,
#     deps = [":LPMS_driver_component_lib"],
# )

# cc_library(
#     name = "LPMS_driver_component_lib",
#     srcs = ["LPMS_driver_component.cc"],
#     hdrs = ["LPMS_driver_component.h"],
#     copts = ['-DMODULE_NAME=\\"LPMS\\"'],
#     deps = [
#         "//cyber",
#         "//modules/common/util:message_util",
#         "//modules/drivers/LPMS/driver",
#     ],
# )


# cpplint()
