name: Diamond

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Free disk space
      run: |
        sudo swapoff -a
        sudo rm -f /swapfile
        sudo apt clean
        docker rmi $(docker image ls -aq)
        df -h
    - name: Signed Diamond Agreement
      run: cp scripts/AGREEMENT.txt ${HOME}/.apollo_agreement.txt
    - name: Pull and Create Container
      run: bash docker/scripts/cyber_start.sh
    # - name: cyber into 
      # run: bash docker/scripts/cyber_into.sh
    - name: docker stockpile
      run: docker exec -u $USER apollo_cyber_$USER df
    - name: Build
      run: docker exec -u $USER apollo_cyber_$USER bash -c "./apollo.sh build"
